PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX food: <http://example.org/food#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?label
WHERE {
    {
        ?individuo rdf:type food:Alergeno .
        ?individuo rdfs:label ?label .
    }
    UNION
    {
        ?individuo rdf:type food:AlergenoPorDerivacao .
        ?individuo rdfs:label ?label .
    }
}